spring:
  application:
    name: trello

  datasource:
    url: jdbc:postgresql://localhost:5432/trello
    username: postgres
    password: Nadi.3344
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true

server:
  port: 8080
